version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodbz_eventapp
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${NAME_DATABASE}
    restart: unless-stopped

volumes:
  mongodb-data:
    driver: local
